### PR TITLE
upgraded Caffe inclusions according to recent Caffe's commits

### PR DESCRIPTION
**Pull request by GiuliaP**
This PR solves this issue: https://github.com/robotology/himrep/issues/7. Hence, now `caffeCoder` compiles with latest `Caffe` code, freshly cloned from their repository.

I have checked that the correctness of the feature extraction is maintained, i.e., that the same feature is computed from the same image, both by this and the previous versions of `Caffe` + `caffeCoder`.

However, I faced a problem which was unexpected, related to the computational time. 
Indeed, latest `Caffe` can make use of `cuDNN version 3.0`, which in turn requires `CUDA 7.5` and, therefore, up-to-date drivers. 
As I was still using `CUDA 6.5` (and `cuDNN version 2.0`) on my system, this time I compiled `Caffe` without the `cuDNN` support and with `CUDA 6.5`, in order to avoid upgrading everything. Unfortunately, I experimented that in this configuration the feature extraction with `caffeCoder` takes around 200ms, while using previous `Caffe` + `caffeCoder` in the same configuration provides features in 12ms.

I investigated more on this and here are my time measurements related to `caffeCoder` feature extraction both on the old and the upgraded system:

| DEVICE | CUDA | cuDNN | precision | Caffe version | time [ms] |
| --- | --- | --- | --- | --- | --- |
| Tesla k40 | 7.5 | 3.0 | double | new | 30 |
| Tesla k40 | 6.5 | - | double | new | 200 |
| Tesla k40 | 6.5 | - | double | old | 10 |
| Tesla k40 | 6.5 | 2.0 | double | old | 10 |
| Tesla k40 | 7.5 | - | float | new | 10 |
| Tesla k40 | 7.5 | 3.0 | float | new | 10 |
| GeForce | 7.5 | 3.0 | double | new | 60 |
| CPU | - | - | - | new | 300 |

So basically it's not clear to me why:
1. Using the newest `Caffe`, on the same configured system the performance is `200 ms` instead of `10 ms` (it seems that using or not `cuDNN` does not make so much difference).
2. In order to obtain 30ms it is required to upgrade everything.
3. Even after the upgrade, I wasn't able to achieve 10ms unless switching to float precision instead of double.

I'll let you know if these measurements can be due to some other reasons (e.g. different Boost/BLAS versions...).
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-166429698%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-166430139%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-193687543%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-193688836%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-201063448%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-202772720%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-205791161%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-205805088%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-207360632%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-207363497%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-207387501%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-207432864%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-208218125%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-208220071%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-208224513%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-209428074%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-215059760%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-215067217%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-215073075%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-215074858%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-216588932%22%2C%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-216603584%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/himrep/pull/10%23issuecomment-166429698%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Perhaps%2C%20it%20might%20be%20worth%20submitting%20these%20results%20to%20%60Caffe%60%20maintainers%20and%20ask%20if%20they%20have%20any%20clue.%22%2C%20%22created_at%22%3A%20%222015-12-21T21%3A27%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%2C%20I%20will.%22%2C%20%22created_at%22%3A%20%222015-12-21T21%3A30%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20that%20now%20Caffe%20should%20have%20introduced%20a%20versioning%20system%2C%20hence%20it%20should%20be%20possible%20to%20check%20Caffe%20version%20and%20include%20headers%20accordingly.%20I%20will%20try%20to%20update%20the%20PR%20soon%20so%20that%20it%20should%20work%20with%20any%20Caffe%20version.%20In%20any%20case%20I%20think%20that%2C%20unless%20one%20avoids%20pulling%20from%20Caffe%27s%20repo%20at%20all%20in%20the%20future%20%28unlikely%29%2C%20we%20will%20be%20forced%20to%20update%20Caffe%20on%20our%20systems%20and%20therefore%20accept%20this%20PR%2C%20despite%20the%20risk%20of%20some%20slowing%20down...%22%2C%20%22created_at%22%3A%20%222016-03-08T09%3A32%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%5Cr%5Cn%5Cr%5CnOf%20course%20we%20should%20not%20constrain%20ourselves%20to%20one%20particular%20version%20of%20Caffe.%22%2C%20%22created_at%22%3A%20%222016-03-08T09%3A38%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40GiuliaP%20any%20news%20on%20that%3F%22%2C%20%22created_at%22%3A%20%222016-03-24T22%3A50%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20%40pattacini%2C%20sorry%20for%20the%20delay%20of%20the%20reply.%20As%20soon%20as%20I%20can%2C%20but%20not%20later%20than%20next%20Tuesday%2C%20I%20will%20do%20what%20I%20anticipated%20above%20%28check%20Caffe%20version%20and%20include%20headers%20accordingly%29%2C%20in%20order%20to%20avoid%20problems%20with%20newer%20or%20older%20Caffe%20code%2C%20testing%20it%20on%20our%20system%20before%20merging%20the%20PR.%20Is%20it%20ok%3F%22%2C%20%22created_at%22%3A%20%222016-03-29T08%3A11%3A35Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22Hi%20%40pattacini%2C%20I%20am%20on%20this%20%3A%29%20I%20have%20posted%20a%20couple%20of%20questions%20on%20caffe%20forums%2C%20since%20I%20do%20not%20know%20exactly%20how%20to%20do%20this%20properly%20and%20I%20have%20been%20googling%20the%20whole%20morning%20without%20success%3A%5Cr%5Cnhttps%3A//groups.google.com/forum/%23%21topic/caffe-users/oOmKmpH1z80%5Cr%5Cnhttps%3A//github.com/BVLC/caffe/issues/3409%5Cr%5CnAlthough%20I%20suspect%20that%20this%20is%20just%20a%20%5C%22basic%5C%22%20cmake%20question%2C%20and%20some%20of%20you%20may%20know.%22%2C%20%22created_at%22%3A%20%222016-04-05T12%3A59%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%20%40GiuliaP%20for%20dealing%20with%20this.%5Cr%5CnI%20think%20our%20cmake%20guru%20%40drdanz%20can%20help%20you%20retrieve%20package%20version%20%3Asmirk%3A.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-04-05T13%3A29%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20have%20opened%20another%20issue%20on%20Caffe%2C%20I%27m%20waiting.%20If%20I%20won%27t%20get%20any%20answer%20in%20a%20few%20days%2C%20I%20will%20tackle%20this%20by%20doing%20as%20I%20described%20in%20the%20opened%20issues%2C%20that%20is%20by%20retrieving%20the%20library%20name%20with%20cmake%20%28e.g.%20%60libcaffe.so.1.0.0-rc3%60%29%20and%20parsing%20it.%22%2C%20%22created_at%22%3A%20%222016-04-08T10%3A15%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40GiuliaP%20aside%20from%20the%20Caffe%20community%27s%20feedback%2C%20did%20you%20have%20a%20chat%20with%20%40drdanz%20about%20the%20standard%20ways%20of%20getting%20package%20information%20via%20%60cmake%60%3F%20It%27d%20be%20nice%20to%20see%20whether%20we%20can%20use%20one%20of%20these%20ways.%22%2C%20%22created_at%22%3A%20%222016-04-08T10%3A24%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Nope%2C%20since%20I%27ve%20been%20at%20the%20university%20these%20days.%20%40drdanz%20can%20we%20discuss%20a%20bit%20on%20monday%3F%22%2C%20%22created_at%22%3A%20%222016-04-08T11%3A24%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22Sure%21%22%2C%20%22created_at%22%3A%20%222016-04-08T13%3A30%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100056%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/drdanz%22%7D%7D%2C%20%7B%22body%22%3A%20%22It%20seems%20that%20I%20was%20already%20doing%20in%20the%20%27correct%27%20way%3A%20https%3A//github.com/BVLC/caffe/issues/3962%5Cr%5Cn%5Cr%5CnHence%20I%27m%20going%20to%20follow%20this%20way%20and%20commit.%22%2C%20%22created_at%22%3A%20%222016-04-11T08%3A10%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40GiuliaP%20could%20you%20also%20have%20a%20chat%20round%20with%20%40drdanz%20anyway%3F%20He%20can%20suggest%20the%20right%20cmake%20directives%20to%20achieve%20the%20result.%22%2C%20%22created_at%22%3A%20%222016-04-11T08%3A16%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes%20but%20due%20to%20an%20unforeseen%20difficulty%20I%20cannot%20be%20at%20IIT%20today%20and%20neither%20tomorrow.%20I%27ll%20do%20this%20on%20my%20own%20now%20and%20wait%20for%20a%20confirmation%20from%20%40drdanz%20before%20pushing%20on%20wednesday.%20%22%2C%20%22created_at%22%3A%20%222016-04-11T08%3A24%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22thanks%20%40drdanz%20for%20the%20help%21%22%2C%20%22created_at%22%3A%20%222016-04-13T13%3A06%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40GiuliaP%20what%20happened%20to%20this%20PR%3F%22%2C%20%22created_at%22%3A%20%222016-04-27T11%3A54%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40pattacini%20It%27s%20ready%20to%20be%20merged.%5Cr%5Cn%5Cr%5CnHowever%2C%20I%20haven%27t%20tested%20it%20on%20the%20_same_%20tesla%20machine%20that%20we%20use%20on%20the%20black%20robot%3A%20I%20have%20tested%20it%20with%20both%20%5C%22older%5C%22%20and%20%5C%22newer%5C%22%20caffe%20versions%2C%20but%20on%20_my_%20tesla%20machine%20%28that%20anyway%20has%20an%20equal%20system%20configuration%20of%20the%20tesla%20machine%20of%20the%20robot%29.%20This%20check%20that%20I%20would%20do%20on%20exactly%20the%20same%20machine%20is%20to%20be%20100%25%20safe%2C%20in%20order%20to%20avoid%20bad%20surprises%20before%20a%20demo.%20The%20reason%20why%20I%20haven%27t%20done%20this%20check%20yet%20is%20that%2C%20as%20you%20may%20have%20seen%2C%20I%27ve%20been%20missing%20for%20a%20week%20due%20to%20personal%20reasons%20and%20I%20don%27t%20know%20when%20I%20will%20be%20back%20to%20IIT%20right%20now%2C%20hope%20next%20week.%5Cr%5Cn%5Cr%5CnAnyway%2C%20the%20test%20to%20check%20that%20it%20works%20with%20%5C%22old%5C%22%20caffe%20%28the%20one%20currently%20in%20use%20on%20the%20black%20robot%2C%20that%20is%20a%20commit%20of%20approximately%20one%20year%20ago%29%20is%20very%20quick%3A%20pulling%20this%20PR%20and%20verifying%20that%20the%20caffeCoder%20runs%20and%20outputs%20features%20without%20errors.%5Cr%5CnThen%2C%20we%20could%20also%20pull%20the%20latest%20commit%20of%20caffe%20in%20a%20different%20location%20and%20verify%20the%20same%20to%20check%20that%20it%20works%20also%20with%20%5C%22newer%5C%22%20versions.%5Cr%5CnIt%20will%20be%20finally%20up%20to%20us%20to%20decide%20whether%20we%20prefer%20to%20stick%20with%20the%20%5C%22old%5C%22%20or%20%5C%22new%5C%22%20caffe%20commits.%22%2C%20%22created_at%22%3A%20%222016-04-27T12%3A30%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ok%20then%2C%20thanks%20%40GiuliaP%20for%20the%20update.%5Cr%5CnWe%20can%20wait%20next%20week.%22%2C%20%22created_at%22%3A%20%222016-04-27T12%3A55%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ok%20thanks%20%40pattacini%20%2C%20sorry%20if%20I%20didn%27t%20add%20any%20comment%20saying%20that%20we%20had%20fixed%20it%20with%20%40drdanz%20.%20I%27ll%20let%20you%20know%20if%20I%20have%20further%20delays.%22%2C%20%22created_at%22%3A%20%222016-04-27T13%3A03%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40pattacini%20%3A%20I%20tested%20this%20PR%20of%20%60caffeCoder%60%20on%20our%20robot%20and%20it%20runs%20without%20runtime%20errors%20%28i.e.%20sending%20features%20out%29%20both%20with%20old%20and%20newest%20%60caffe%60%20repositories.%5Cr%5Cn%5Cr%5CnOne%20last%20note%3A%20in%20the%20end%20I%20still%20left%20the%20old%20%60caffe%60%20on%20our%20system%2C%20since%2C%20as%20mentioned%20at%20the%20very%20beginning%20of%20this%20PR%2C%20with%20CUDA%206.5%20it%27s%2010x%20faster.%20To%20recover%20%27part%27%20of%20the%20original%20time%20performance%20with%20new%20%60caffe%60%2C%20as%20mentioned%20we%20should%20upgrade%20also%20NVIDIA%20driver%2C%20CUDA%2C%20and%20cuDNN.%22%2C%20%22created_at%22%3A%20%222016-05-03T16%3A40%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6449556%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/GiuliaP%22%7D%7D%2C%20%7B%22body%22%3A%20%22Well%20done%2C%20merging.%22%2C%20%22created_at%22%3A%20%222016-05-03T17%3A25%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/himrep/pull/10#issuecomment-166429698'>General Comment</a></b>
- <a href='https://github.com/pattacini'></a> Perhaps, it might be worth submitting these results to `Caffe` maintainers and ask if they have any clue.
- <a href='https://github.com/GiuliaP'></a> Yes, I will.
- <a href='https://github.com/GiuliaP'></a> I think that now Caffe should have introduced a versioning system, hence it should be possible to check Caffe version and include headers accordingly. I will try to update the PR soon so that it should work with any Caffe version. In any case I think that, unless one avoids pulling from Caffe's repo at all in the future (unlikely), we will be forced to update Caffe on our systems and therefore accept this PR, despite the risk of some slowing down...
- <a href='https://github.com/pattacini'></a> :+1:
  Of course we should not constrain ourselves to one particular version of Caffe.
- <a href='https://github.com/pattacini'></a> @GiuliaP any news on that?
- <a href='https://github.com/GiuliaP'></a> Hi @pattacini, sorry for the delay of the reply. As soon as I can, but not later than next Tuesday, I will do what I anticipated above (check Caffe version and include headers accordingly), in order to avoid problems with newer or older Caffe code, testing it on our system before merging the PR. Is it ok?
- <a href='https://github.com/GiuliaP'></a> Hi @pattacini, I am on this :) I have posted a couple of questions on caffe forums, since I do not know exactly how to do this properly and I have been googling the whole morning without success:
  https://groups.google.com/forum/#!topic/caffe-users/oOmKmpH1z80
  https://github.com/BVLC/caffe/issues/3409
  Although I suspect that this is just a "basic" cmake question, and some of you may know.
- <a href='https://github.com/pattacini'></a> Thanks @GiuliaP for dealing with this.
  I think our cmake guru @drdanz can help you retrieve package version :smirk:.
- <a href='https://github.com/GiuliaP'></a> I have opened another issue on Caffe, I'm waiting. If I won't get any answer in a few days, I will tackle this by doing as I described in the opened issues, that is by retrieving the library name with cmake (e.g. `libcaffe.so.1.0.0-rc3`) and parsing it.
- <a href='https://github.com/pattacini'></a> @GiuliaP aside from the Caffe community's feedback, did you have a chat with @drdanz about the standard ways of getting package information via `cmake`? It'd be nice to see whether we can use one of these ways.
- <a href='https://github.com/GiuliaP'></a> Nope, since I've been at the university these days. @drdanz can we discuss a bit on monday?
- <a href='https://github.com/drdanz'></a> Sure!
- <a href='https://github.com/GiuliaP'></a> It seems that I was already doing in the 'correct' way: https://github.com/BVLC/caffe/issues/3962
  Hence I'm going to follow this way and commit.
- <a href='https://github.com/pattacini'></a> @GiuliaP could you also have a chat round with @drdanz anyway? He can suggest the right cmake directives to achieve the result.
- <a href='https://github.com/GiuliaP'></a> Yes but due to an unforeseen difficulty I cannot be at IIT today and neither tomorrow. I'll do this on my own now and wait for a confirmation from @drdanz before pushing on wednesday.
- <a href='https://github.com/GiuliaP'></a> thanks @drdanz for the help!
- <a href='https://github.com/pattacini'></a> @GiuliaP what happened to this PR?
- <a href='https://github.com/GiuliaP'></a> @pattacini It's ready to be merged.
  However, I haven't tested it on the _same_ tesla machine that we use on the black robot: I have tested it with both "older" and "newer" caffe versions, but on _my_ tesla machine (that anyway has an equal system configuration of the tesla machine of the robot). This check that I would do on exactly the same machine is to be 100% safe, in order to avoid bad surprises before a demo. The reason why I haven't done this check yet is that, as you may have seen, I've been missing for a week due to personal reasons and I don't know when I will be back to IIT right now, hope next week.
  Anyway, the test to check that it works with "old" caffe (the one currently in use on the black robot, that is a commit of approximately one year ago) is very quick: pulling this PR and verifying that the caffeCoder runs and outputs features without errors.
  Then, we could also pull the latest commit of caffe in a different location and verify the same to check that it works also with "newer" versions.
  It will be finally up to us to decide whether we prefer to stick with the "old" or "new" caffe commits.
- <a href='https://github.com/pattacini'></a> Ok then, thanks @GiuliaP for the update.
  We can wait next week.
- <a href='https://github.com/GiuliaP'></a> Ok thanks @pattacini , sorry if I didn't add any comment saying that we had fixed it with @drdanz . I'll let you know if I have further delays.
- <a href='https://github.com/GiuliaP'></a> @pattacini : I tested this PR of `caffeCoder` on our robot and it runs without runtime errors (i.e. sending features out) both with old and newest `caffe` repositories.
  One last note: in the end I still left the old `caffe` on our system, since, as mentioned at the very beginning of this PR, with CUDA 6.5 it's 10x faster. To recover 'part' of the original time performance with new `caffe`, as mentioned we should upgrade also NVIDIA driver, CUDA, and cuDNN.
- <a href='https://github.com/pattacini'></a> Well done, merging.

<a href='https://www.codereviewhub.com/robotology/himrep/pull/10?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/himrep/pull/10?approve=1'></a>&nbsp;<a href='https://github.com/robotology/himrep/pull/10'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by pattacini** [comment]
Perhaps, it might be worth submitting these results to `Caffe` maintainers and ask if they have any clue.

**Comment by GiuliaP** [comment]
Yes, I will.

**Comment by GiuliaP** [comment]
I think that now Caffe should have introduced a versioning system, hence it should be possible to check Caffe version and include headers accordingly. I will try to update the PR soon so that it should work with any Caffe version. In any case I think that, unless one avoids pulling from Caffe's repo at all in the future (unlikely), we will be forced to update Caffe on our systems and therefore accept this PR, despite the risk of some slowing down...

**Comment by pattacini** [comment]
:+1: 

Of course we should not constrain ourselves to one particular version of Caffe.

**Comment by pattacini** [comment]
@GiuliaP any news on that?

**Comment by GiuliaP** [comment]
Hi @pattacini, sorry for the delay of the reply. As soon as I can, but not later than next Tuesday, I will do what I anticipated above (check Caffe version and include headers accordingly), in order to avoid problems with newer or older Caffe code, testing it on our system before merging the PR. Is it ok?

**Comment by GiuliaP** [comment]
Hi @pattacini, I am on this :) I have posted a couple of questions on caffe forums, since I do not know exactly how to do this properly and I have been googling the whole morning without success:
https://groups.google.com/forum/#!topic/caffe-users/oOmKmpH1z80
https://github.com/BVLC/caffe/issues/3409
Although I suspect that this is just a "basic" cmake question, and some of you may know.

**Comment by pattacini** [comment]
Thanks @GiuliaP for dealing with this.
I think our cmake guru @drdanz can help you retrieve package version :smirk:.

**Comment by GiuliaP** [comment]
I have opened another issue on Caffe, I'm waiting. If I won't get any answer in a few days, I will tackle this by doing as I described in the opened issues, that is by retrieving the library name with cmake (e.g. `libcaffe.so.1.0.0-rc3`) and parsing it.

**Comment by pattacini** [comment]
@GiuliaP aside from the Caffe community's feedback, did you have a chat with @drdanz about the standard ways of getting package information via `cmake`? It'd be nice to see whether we can use one of these ways.

**Comment by GiuliaP** [comment]
Nope, since I've been at the university these days. @drdanz can we discuss a bit on monday?

**Comment by drdanz** [comment]
Sure!

**Comment by GiuliaP** [comment]
It seems that I was already doing in the 'correct' way: https://github.com/BVLC/caffe/issues/3962

Hence I'm going to follow this way and commit.

**Comment by pattacini** [comment]
@GiuliaP could you also have a chat round with @drdanz anyway? He can suggest the right cmake directives to achieve the result.

**Comment by GiuliaP** [comment]
Yes but due to an unforeseen difficulty I cannot be at IIT today and neither tomorrow. I'll do this on my own now and wait for a confirmation from @drdanz before pushing on wednesday.

**Comment by GiuliaP** [comment]
thanks @drdanz for the help!

**Comment by pattacini** [comment]
@GiuliaP what happened to this PR?

**Comment by GiuliaP** [comment]
@pattacini It's ready to be merged.

However, I haven't tested it on the _same_ tesla machine that we use on the black robot: I have tested it with both "older" and "newer" caffe versions, but on _my_ tesla machine (that anyway has an equal system configuration of the tesla machine of the robot). This check that I would do on exactly the same machine is to be 100% safe, in order to avoid bad surprises before a demo. The reason why I haven't done this check yet is that, as you may have seen, I've been missing for a week due to personal reasons and I don't know when I will be back to IIT right now, hope next week.

Anyway, the test to check that it works with "old" caffe (the one currently in use on the black robot, that is a commit of approximately one year ago) is very quick: pulling this PR and verifying that the caffeCoder runs and outputs features without errors.
Then, we could also pull the latest commit of caffe in a different location and verify the same to check that it works also with "newer" versions.
It will be finally up to us to decide whether we prefer to stick with the "old" or "new" caffe commits.

**Comment by pattacini** [comment]
Ok then, thanks @GiuliaP for the update.
We can wait next week.

**Comment by GiuliaP** [comment]
Ok thanks @pattacini , sorry if I didn't add any comment saying that we had fixed it with @drdanz . I'll let you know if I have further delays.

**Comment by GiuliaP** [comment]
@pattacini : I tested this PR of `caffeCoder` on our robot and it runs without runtime errors (i.e. sending features out) both with old and newest `caffe` repositories.

One last note: in the end I still left the old `caffe` on our system, since, as mentioned at the very beginning of this PR, with CUDA 6.5 it's 10x faster. To recover 'part' of the original time performance with new `caffe`, as mentioned we should upgrade also NVIDIA driver, CUDA, and cuDNN.

**Comment by pattacini** [comment]
Well done, merging.

**Pull request merged**
