### PR TITLE
Use of mutex in linearClassifierModule restyled

### PR DESCRIPTION
**Pull request by pattacini**
Deep restyling of the use of mutex within the `linearClassifierModule`.
It might fix also problems due to #8.

/cc @Tobias-Fischer @vtikha

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
By just going through the code, it's looking good to me. I'll try to find some time today or tomorrow to give it a try on the robot. Thanks @pattacini!

**Comment by maxime-petit** [comment]
Hi,
We've just given it a try and unfortunately it's not working in the current state. `linearClassifierModule` is stuck after retrieving the `objList` command. This is because the `run()` method is locking the mutex, and never unlocking it (it's more or less a `while(true)` loop).
Could you please have a look? We would give it another try later today.

Thanks!

**Comment by pattacini** [comment]
My bad, thanks @maxime-petit; I didn't see it was a `Thread::run()` and not a `RateThread::run()`. Should be fixed.

**Comment by Tobias-Fischer** [comment]
Hi @ugo,
Thanks for the quick change. However, the `LockGuard` needs to be moved after the `Bottle *p=featuresPort.read();` (or better: after the continue), otherwise the `read` is blocking the thread - and the mutex.

Thanks :)

**Comment by pattacini** [comment]
PR open to contributions :smirk:

**Comment by Tobias-Fischer** [comment]
@maxime-petit and I just gave it a try, and it seems to work just fine. I would be happy to merge if there are no objections :+1:

**Comment by pattacini** [comment]
Cool; go ahead!

**Pull request merged**
