### PR TITLE
Pick up caffe version on OS X

### PR DESCRIPTION
**Pull request by BrutusTT**
The caffe lib name on OS X differs from linux in the way that it does not have the ".so" extension. Usually caffe compiles with names like "libcaffe.[major].[minor].[patch]-[patch2].dylib" on OS X.

That means the ".so" part should be optional.

### CODE REVIEW

**Comment by pattacini** [comment]
Hi @GiuliaP 
Could you please take this PR?

**Comment by GiuliaP** [comment]
Yes. It is a simple modification, but I just want to try it on Mac OS and Linux before. I hope to manage in the next days.

**Comment by GiuliaP** [comment]
I checked. In this way, on OS X, the version is not parsed correctly. 
The output of 
```
if("${CAFFE_SONAME}" MATCHES "libcaffe.(so.)?([0-9]+).([0-9]+).([0-9]+)(-(.+))?")
    set(CAFFE_MAJOR "${CMAKE_MATCH_2}")
    message("${CMAKE_MATCH_2}")
    set(CAFFE_MINOR "${CMAKE_MATCH_3}")
    message("${CMAKE_MATCH_3}")
    set(CAFFE_PATCH "${CMAKE_MATCH_4}")
    message("${CMAKE_MATCH_4}")
    set(CAFFE_PATCH2 "${CMAKE_MATCH_6}")
    message("${CMAKE_MATCH_6}")
    set(CAFFE_VERSION_STRING "${CAFFE_MAJOR}.${CAFFE_MINOR}.${CAFFE_PATCH}")
    ...
```
gives
```
   1
   0
   0
   rc5.dylib
```
which is not ok.

In any case, I think that the way we parse caffe's soname should be modified (for this I asked also @drdanz to help me).

Finally, as of today, we were not officially supporting OS X, but only Ubuntu 16.04, in case we decide to extend the support to OS X also the installation instructions should be updated.

To conclude, @pattacini @BrutusTT , if it is ok for you, in next months I will take care of this and also other [issues](https://github.com/robotology/himrep/issues), to see also if we can extend the support to OS X (seems reasonable).

**Comment by pattacini** [comment]
That's fine with me.
If @BrutusTT has no objections, we can close this PR.

**Comment by BrutusTT** [comment]
Yes, please close it. I had not too much time to look more into it anyways. For me the solution worked but of course I see that it does not produce the proper solution. I am not aware that other things are broken for OS X. I used himrep now since a while and it worked for me except for the finding of the caffe lib (I only saw that it was checked for the major release number for backwards compatibility). Is there more that I need to be aware of in terms of compatibility that I might not have seen yet?

**Comment by BrutusTT** [comment]
Hmm out of curiosity, I just double checked with my current caffe installation. Why is 1.0.0-rc5 not ok ? My current installed lib is called libcaffe.1.0.0-rc5.dylib. As far as I can tell, its working for me. Should I have a different one?

**Comment by pattacini** [comment]
@GiuliaP any comments on this?

**Comment by GiuliaP** [comment]
Hi, sorry for the delay. No @BrutusTT , you are right, at present the major release number is the only required thing to check. This is also the reason why your PR actually works, since CAFFE_PATCH2 is not checked against. However, since we previously decided to parse the version string completely, I would like to either ensure that this is parsed correctly also on OS X, or eventually decide to parse only the major release number.

**Pull request closed without merging**
